/*
 * This source file was generated by the Gradle 'init' task
 */
package exemplo1;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication

//torna a classe capaz de receber requisicao
@RestController
//direciona a requisicao, define a rota
@RequestMapping("/app")

public class App {

    //qd o usuario fizer um get em /app, retornar recurso no metodo em sequencia
    @GetMapping("/ola")
    public String ola() {
        return "Olá,";
    }

    //é possível definir varias rotas
    @GetMapping("/mundo")
    public String Mundo() {
        return "mundo!";
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
